import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1800, height: 1200 } });
await p.goto("http://localhost:3200/architecture", { waitUntil: "networkidle" });
await p.waitForTimeout(2500);
const tab = p.locator("[data-canvas] button", { hasText: /security-group/ }).first();
await tab.scrollIntoViewIfNeeded();
await tab.click();
await p.waitForTimeout(500);
console.log("open after click :", await p.locator('[aria-label="close list"]').count());
await p.locator('[aria-label="close list"]').first().click();
await p.waitForTimeout(500);
console.log("open after X     :", await p.locator('[aria-label="close list"]').count());
await tab.click();
await p.waitForTimeout(400);
await tab.click();
await p.waitForTimeout(400);
console.log("toggle off by tab:", await p.locator('[aria-label="close list"]').count());
await b.close();
